name: first workflow

on:
 push

jobs:
  firstjob:
     runs-on: ubuntu_latest
     steps:
     - name: first step
       run: echo "hello world"

     - name: second step
       run: ls -l

     - name: third step
       id: third_step
       run: pwd >> GITHUB_OUTPUT

     - name: fourth step
       run: echo "steps.third_step.present_Working_directory"





#        name: second workflow
# on:
#  push:
# jobs:
#   second:
#     runs-on: self-hosted
#     steps:
#     - name: runs the first job
#       run: echo "run's the first job"

#     - name: run the second job
#       run: echo "print run the second job"

     
