name: first workflow

on:
- push
- workflow_dispatch

jobs:
  firstjob:
     runs-on: ubuntu_latest
     steps:
     - name: first step
       run: echo "hello world"

     - name: second step
       run: ls -l

     - name: third step
       id: third_step
       run: pwd >> GITHUB_OUTPUT

     - name: fourth step
       run: echo "steps.third_step.present_Working_directory"

     
